FROM quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/intermediate-sigstore@sha256:83e03294d6dfe8443762a735b2abb1171043cbfb93694a459e4432e520acf9a2 AS sigstore-binaries
FROM quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/intermediate-ec@sha256:83e03294d6dfe8443762a735b2abb1171043cbfb93694a459e4432e520acf9a2 AS ec-binaries
FROM registry.access.redhat.com/ubi9/httpd-24@sha256:965f7b03ae8f45228bad765ce47bc8956711e854213df0e4cee8623d51317b0a


RUN mkdir -p /var/www/html/clients/darwin && \
    mkdir -p /var/www/html/clients/linux && \
    mkdir -p /var/www/html/clients/windows

COPY --from=sigstore-binaries /copies/cosign/cosign-darwin-amd64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/cosign/cosign-darwin-arm64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/cosign/cosign-linux-amd64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/cosign/cosign-linux-arm64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/cosign/cosign-linux-ppc64le.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/cosign/cosign-linux-s390x.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/cosign/cosign-windows-amd64.gz /var/www/html/clients/windows

COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_darwin_amd64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_darwin_arm64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_linux_amd64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_linux_arm64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_linux_ppc64le.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_linux_s390x.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/gitsign/gitsign_cli_windows_amd64.exe.gz /var/www/html/clients/windows

COPY --from=sigstore-binaries /copies/rekor/rekor_cli_darwin_amd64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_darwin_arm64.gz /var/www/html/clients/darwin
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_linux_amd64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_linux_arm64.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_linux_ppc64le.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_linux_s390x.gz /var/www/html/clients/linux
COPY --from=sigstore-binaries /copies/rekor/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows

COPY --from=ec-binaries /copies/ec/ec_darwin_amd64.gz /var/www/html/clients/darwin
COPY --from=ec-binaries /copies/ec/ec_darwin_arm64.gz /var/www/html/clients/darwin
COPY --from=ec-binaries /copies/ec/ec_linux_amd64.gz /var/www/html/clients/linux
COPY --from=ec-binaries /copies/ec/ec_linux_arm64.gz /var/www/html/clients/linux
COPY --from=ec-binaries /copies/ec/ec_linux_ppc64le.gz /var/www/html/clients/linux
COPY --from=ec-binaries /copies/ec/ec_linux_s390x.gz /var/www/html/clients/linux
COPY --from=ec-binaries /copies/ec/ec_windows_amd64.exe.gz /var/www/html/clients/windows

RUN   mv /var/www/html/clients/darwin/gitsign_cli_darwin_amd64.gz /var/www/html/clients/darwin/gitsign-amd64.gz && \
      mv /var/www/html/clients/darwin/gitsign_cli_darwin_arm64.gz /var/www/html/clients/darwin/gitsign-arm64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_amd64.gz /var/www/html/clients/linux/gitsign-amd64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_arm64.gz /var/www/html/clients/linux/gitsign-arm64.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_ppc64le.gz /var/www/html/clients/linux/gitsign-ppc64le.gz && \
      mv /var/www/html/clients/linux/gitsign_cli_linux_s390x.gz /var/www/html/clients/linux/gitsign-s390x.gz && \
      mv /var/www/html/clients/windows/gitsign_cli_windows_amd64.exe.gz /var/www/html/clients/windows/gitsign-amd64.gz

RUN mv /var/www/html/clients/darwin/rekor_cli_darwin_amd64.gz /var/www/html/clients/darwin/rekor-cli-amd64.gz && \
      mv /var/www/html/clients/darwin/rekor_cli_darwin_arm64.gz /var/www/html/clients/darwin/rekor-cli-arm64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_amd64.gz /var/www/html/clients/linux/rekor-cli-amd64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_arm64.gz /var/www/html/clients/linux/rekor-cli-arm64.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_ppc64le.gz /var/www/html/clients/linux/rekor-cli-ppc64le.gz && \
      mv /var/www/html/clients/linux/rekor_cli_linux_s390x.gz /var/www/html/clients/linux/rekor-cli-s390x.gz && \
      mv /var/www/html/clients/windows/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows/rekor-cli-amd64.gz

RUN mv /var/www/html/clients/darwin/ec_darwin_amd64.gz /var/www/html/clients/darwin/ec-amd64.gz && \
      mv /var/www/html/clients/darwin/ec_darwin_arm64.gz /var/www/html/clients/darwin/ec-arm64.gz && \
      mv /var/www/html/clients/linux/ec_linux_amd64.gz /var/www/html/clients/linux/ec-amd64.gz && \
      mv /var/www/html/clients/linux/ec_linux_arm64.gz /var/www/html/clients/linux/ec-arm64.gz && \
      mv /var/www/html/clients/linux/ec_linux_ppc64le.gz /var/www/html/clients/linux/ec-ppc64le.gz && \
      mv /var/www/html/clients/linux/ec_linux_s390x.gz /var/www/html/clients/linux/ec-s390x.gz && \
      mv /var/www/html/clients/windows/ec_windows_amd64.exe.gz /var/www/html/clients/windows/ec-amd64.gz

RUN mv /var/www/html/clients/darwin/cosign-darwin-amd64.gz /var/www/html/clients/darwin/cosign-amd64.gz && \
      mv /var/www/html/clients/windows/cosign-windows-amd64.gz /var/www/html/clients/windows/cosign-amd64.gz && \
      mv /var/www/html/clients/darwin/cosign-darwin-arm64.gz /var/www/html/clients/darwin/cosign-arm64.gz && \
      mv /var/www/html/clients/linux/cosign-linux-ppc64le.gz /var/www/html/clients/linux/cosign-ppc64le.gz && \
      mv /var/www/html/clients/linux/cosign-linux-amd64.gz /var/www/html/clients/linux/cosign-amd64.gz && \
      mv /var/www/html/clients/linux/cosign-linux-s390x.gz /var/www/html/clients/linux/cosign-s390x.gz && \
      mv /var/www/html/clients/linux/cosign-linux-arm64.gz /var/www/html/clients/linux/cosign-arm64.gz

CMD run-httpd

LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container" \
      name="trusted-artifact-signer-serve-cli-container" \
      version="0.0.1" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries" \
      description="Serves Trusted Artifact Signer CLI binaries from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries" \
      io.openshift.tags="cosign, gitsign, rekor, ec, cli, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"